%YAML 1.0
---

# RISC OS build file to execute on https://build.riscos.online/

# Source is optional (NYI), and should be a URL to source the content from
#source: <url>

# Defines a list of jobs which will be performed.
# Only 1 job will currently be executed.
jobs:
  build:
    # Env defines system variables which will be used within the environment.
    # Multiple variables may be assigned.
    env:
      "Sys$Environment": ROBuild
      "BUILD32": 1

      # Faster building using the host toolchain
      "Alias$AMU": "HostAMU %*0"

    # Directory to change to before running script
    #dir: <working directory>

    # Commands which should be executed to perform the build.
    # The build will terminate if any command returns a non-0 return code or an error.
    script:

      # Build library
      - echo
      - echo *** Build the library ***
      - amu -f MakefileLib export

      # Test the library
      - echo
      - echo *** Build and run library tests ***
      - amu -f MakefileTest
      - aif32.oras-test

      # Build command-line tool
      - echo
      - echo *** Build command-line tool ***
      - amu -f Makefile

      # Stage all distributable components for the returned archive.
      - echo
      - echo *** Copying results ***
      - cdir Install
      - cdir Install.aif32
      - Copy aif32.oras-test Install.aif32.oras-test ~CFVR
      - Copy aif32.oras Install.aif32.oras ~CFVR
      - cdir Install.Lib
      - Copy <Exports$Dir>.Lib.ORAS Install.Lib.ORAS ~CVRF
      - cdir Install.HTML
      - Copy documentation Install.HTML ~CFVR

      # Done!
      - echo
      - echo *** SUCCESS ***

    # Outputs from the build are defined in artifacts
    # These are a list of artifacts to report directories or files.
    # Only a single item is currently supported.
    artifacts:
      # Each element of the artifacts should have a path key, which gives the file or
      # directory to return.
      - path: Install
